---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
  namespace: basics
spec:
  hosts:
  - "basics.example.com"
  - "basics.apigw.svc.cluster.local"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: frontend
        port:
          number: 80
